### ISSUE TITLE
UPS tab not showing in XGUI

### ISSUE THREAD

**Issue by SkyFoxCoder** [TeamUlysses/ups#1]
### Steps to reproduce
1. Install ULX, Ulib & UPS (all from GitHub)
2. Start the server, Join & Open XGUI -> Settings tab.

### How I installed the addons:
Current folder: garrysmod/addons
`git clone https://github.com/TeamUlysses/ulx`
`git clone https://github.com/TeamUlysses/ulib`
`git clone https://github.com/TeamUlysses/ups`

After running the commands, folder structure:
garrysmod/addons/ulx/lua...
garrysmod/addons/ulib/lua...
garrysmod/addons/ups/lua...

### Expected behavior
I should see the UPS Tab in the Settings Tab in XGUI.

### Actual behavior
The UPS Tab is not there.

### Version
Result of "ulx version":
ULib v2.61d (10/26/16)
ULX v3.71d (11/12/16)

#### (If requested I will provide the server's addon list)

**Comment by Nayruden** [comment]
UPS is not supposed to appear in XGUI -- it's within the "Q" menu (spawn
menu).

**Comment by SkyFoxCoder** [comment]
Oh, right, I mixed it with another addon that add's a tab there, I forgot the name tho :/ It has a yellow Shield for the icon, any idea of the name of it?

**Comment by SkyFoxCoder** [comment]
Found it, thx for your reply!
( http://forums.ulyssesmod.net/index.php?topic=5269.0 )
